database:
  host: "localhost:5432/"
  user: postgres
  password: pwd

shop:
  offers:
    chest-key:
      item: "chest-key"
      amount: 1
      price:
        required-points: 100
        item: "iron_ingot"
        amount: 2
        second-item: "gold_ingot"
        second-amount: 1
    mending-Infinity-bow:
      item: "mending-Infinity-bow"
      amount: 1
      price:
        required-points: 3000
        item: "bow"
        amount: 1
        second-item: "netherite_ingot"
        second-amount: 3

help:
  root: "§a----- §bHilfe §a----- \n\n§aNutze §b/help event §afür kommende Events \n§aNutze §b/help command §afür eine Command-Übersicht \n§aNutze §b/help support §afür Infos zum Support \n\n§a----- §bHilfe §a-----"
  event-info: |-
    Es wird an jedem Wochenende ein Event geben, in dem du zusätzliche Punkte bekommen kannst.
    - §aEvent am 10.12§r: Replika
    - §aEvent am 17.12§r: PvE Waves
    - §aEvent am 23.12§r: Rätsel-Labyrinth
  support-info: |-
    Wenn du support erhalten möchtest, kannst du dich jeder Zeit an das Server-Team melden.
    Du kannst entweder im Minecraft-Chat mit einem Team-Mitglied Kontakt aufnehmen oder dich auf dem §2Slimecloud Discord§r an uns wenden.
    Zusätzlich kannst du §b/bug§r und §b/feedback§r verwenden, um auf ein Formular weitergeleitet zu werden.
  command-info:
    rules: "Zeigt die Regeln des Hard-SMP Events an"
    spawn: "Teleportiert dich zum Spawn-Dorf"
    msg: "Sende eine private Nachricht zu einem anderen Spieler"
    formatting: "Zeige verfügbare Formations-Zeichen für den Chat an"
    help: "Zeigt die Hilfe zu Kategorien oder Befehlen an"
    feedback: "Zeigt den Link zum Feedback-Formular"
    bug: "Zeigt den Link zum Bugreport-Formular"
    leaderboard: "Zeigt das aktuelle Punkte-Leaderboard an"

rules:
  Discord Regeln: "Auf dem Minecraft Server gelten die gleichen regeln wie auf dem Slimecloud Discord Server. Verwarnung in Minecraft führen auch zu Verwarnungen in Discord!"
  Allgemeine Chatregeln:
    1: "Keine Beleidigungen"
    2: "Kein Mobbing"
    3: "Kein Spammen"
    4: "..."
  Fairness: "Unfaires Spielen wie Griefing oder Hacking ist nicht erlaubt. Als Client-Modifikationen sind nur Optifine oder ähnliche (z.B. Sodium) zulässig!"
  Lags: "Das bewusste verursachen von Server-Lags ist verboten! Redstone-Mechanismen sollten ausgeleuchtet und performant gebaut werden"
  Teaming: "Teaming is grundsätzlich verboten, um das Event für alle Spieler fair zu halten. §l§cKURZE§r§a Zweck-Allianzen und Tauschgeschäfte sind erlaubt"
  Fehler: "Das aktive suchen und ausnutzen von Bugs ist verboten. Solltest du einen Fehler finden, melde ihn bitte mit /bug"
  Unwissenheit: "Unwissenheit schützt nicht vor Strafe! Jeder Spieler ist für seinen Account verantwortlich!"
  Team: "Das Team behält sich das Recht vor, die Regeln jederzeit anzupassen und unangemessenes Verhalten zu ahnden"

ui:
  custom-formatting:
    #rank #1
    v: "#fcd217"
    #rank #2
    w: "#bdbdbd"
    #rank #3
    z: "#bf8970"
    #better green (slime green)
    ä: "#88D657"

  scoreboard:
    title: "\uE001"
    text:
      #every format has to start with a § if the rank are no custom unicode
      default: "%rank. %name   §u%points"
      rank_1: "§l§6%rank. %name   §r§u%points"
      rank_2: "§l§i%rank. %name   §r§u%points"
      rank_3: "§l§y%rank. %name   §r§u%points"

  tablist:
    header: "§j-----  §2Hard-SMP  §j-----"
    prefix: "§8[§7%prefix§8]"
    name: "%prefix §r%name  §p%points"
    footer: "§j---  §7[%tps §8TPS§7]  §j---"

  chat:
    prefix: "§7[%prefix§7]"
    #colr = color rank
    #coln = color name
    format: "%colr#%rank %prefix %coln%name: "
    color:
      name_default: "§ä"
      name_1: "§v"
      name_2: "§w"
      name_3: "§z"

      rank_default: "§7"
      rank_1: "§v"
      rank_2: "§w"
      rank_3: "§z"

verify:
  code-length: 5

discord:
  token: xxx
  console-channel: 123
  netrunner-role: 123

teamchat:
  messageFormat: "§8[§äTeam§bChat§8] §c%player§7:"
  messageColor: "§6"

feedback:
  link: "test"

bugform:
  link: "test"

leaderboard:
  playersPerPage: 10
