database:
  host: "localhost:5432/"
  user: postgres
  password: pwd

shop:
  offers:
    chest-key:
      item: "chest-key"
      amount: 1
      price:
        item: "iron_ingot"
        amount: 2
        second-item: "gold_ingot"
        second-amount: 1
verify:
  code-length: 5

discord:
  token: xxx
