database:
  host: "localhost:5432/"
  user: postgres
  password: pwd

shop:
  offers:
    chest-key:
      item: "chest-key"
      amount: 1
      price:
        item: "iron_ingot"
        amount: 2
        second-item: "gold_ingot"
        second-amount: 1

help:
  root: "Dies ist der Help-command. Verwende die verfügbaren Unterbefehle um informationen über eine Kategorie zu erhalten."
  event-info: |-
    Willkommen beim §cHard-SMP (Das 'S' steht für Schleim)§r Event. Dies ist ein Minecraft-Server Projekt, das über den §9Dezember 2023§r läuft.
    Am Spawn befindet sich ein kleines Dorf, an dem du dich mit §3anderen Spielern treffen§r, §6kleine Secrets finden§r und den §aShop besuchen§r, der besondere Items zur Verfügung stellt.
    
    Durch verschiedene Statistiken und Sammeln von Achievements kannst ud Punkte sammeln, mit denen am Ende des Events der Gewinner festgestellt wird.
    Um das Event fair für alle Teilnehmer zu halten, sind §4TEAMS VERBOTEN§r.
    
    Jede Woche wird es §ezusätzlich Events§r geben, an denen du teilnehmen kannst. Sie decken §2unterschiedliche Gebiete von Minecraft§r ab, es ist also für jeden was dabei.
    Mit den Events kannst du §cextra Punkte verdienen§r, die dir Helfen können, das §egesamte Hard-SMP Event§r für dich zu entscheiden.
    
    Aber Achtung! Abhängig von deiner §eSpielzeit§r werden Punkte weniger Wert. Du solltest deine §cSpielzeit auf dem Server also Produktiv nutzen§r...
    
    Viel Spaß!
  support-info: |-
    Wenn du support erhalten möchtest, kannst du dich jeder Zeit an das Server-Team melden.
    Du kannst entweder im Minecraft-Chat mit einem Team-Mitglied Kontakt aufnehmen oder dich auf dem §2Slimecloud Discord§r an uns wenden.
    Zusätzlich kannst du §b/bug§r und §b/feedback§r verwenden, um auf ein Formular weitergeleitet zu werden.
  command-info:
    rules: "Zeigt die Regeln des Hard-SMP Events an."

rules:
  1: "test1"
  2: "test2"

ui:
  custom-formatting:
    v: "#fcd217"
    w: "#bdbdbd"
    z: "#bf8970"

  scoreboard:
    title: "§2Hard-SMP"
    text:
      default: "%rank. %name   §u%points"
      rank_1: "§l§6%rank. %name   §r§u%points"
      rank_2: "§l§i%rank. %name   §r§u%points"
      rank_3: "§l§y%rank. %name   §r§u%points"

  tablist:
    header: "§j-----  §2Hard-SMP  §j-----"
    prefix: "§8[§7%prefix§8]"
    name: "%prefix §r%name  §p%points"
    footer: "§j---  §7[%tps §8TPS§7]  §j---"

  chat:
    prefix: "§7[%prefix§7]"
    #colr = color rank
    #coln = color name
    format: "%colr#%rank %prefix %coln%name: "
    color:
      name_default: "§a"
      name_1: "§v"
      name_2: "§w"
      name_3: "§z"

      rank_default: "§7"
      rank_1: "§v"
      rank_2: "§w"
      rank_3: "§z"

verify:
  code-length: 5

discord:
  token: xxx

teamchat:
  messageFormat: "§8[§aTeam§bChat§8] §c%player§7:"
  messageColor: "§6"
